name: finandina_prueba
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Versioning for the application
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# Consider running `flutter pub upgrade --major-versions` to upgrade dependencies.
# To see available updates, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.0.0+2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for good coding practices.
  flutter_lints: ^4.0.0

flutter:
  # Ensure that Material Icons font is included for use in the app.
  uses-material-design: true

  # Assets section
  assets:
    - assets/img/

  # To add custom fonts to your application, add a fonts section here.
  # Each entry should have a "family" key with the font family name, and a "fonts" key with a list.
  # For example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
